curl --request POST \
  --url https://api.firecrawl.dev/v2/scrape \
  --header "Authorization: Bearer $token" \
  --header 'Content-Type: application/json' \
  --data '
{
  "url": "https://zh.wikipedia.org/wiki/%E5%9C%8B%E5%AE%B6%E5%92%8C%E5%9C%B0%E5%8D%80%E9%A0%82%E7%B4%9A%E5%9F%9F",
  "formats": ["markdown"],
  "onlyMainContent": true,
  "includeTags": [],
  "excludeTags": [
      "script",
      "style",
      "noscript",
      "form",
      "input",
      "button",
      "select",
      "textarea",
      "nav",
      ".nav",
      ".navbar",
      ".navigation",
      ".menu",
      ".menubar",
      "header",
      "footer",
      "aside",
      "#comments",
      "#disqus_thread",
      "[class*=\"logo\"]",
      "[class*=\"brand\"]",
      "[id*=\"logo\"]",
      "img[alt*=\"logo\"]",
      "img[src*=\"logo\"]",
      "[id*=\"brand\"]",
      "[class^=\"category--\"]",
      "[id^=\"category--\"]",
      "[class$=\"--category\"]",
      "[id$=\"--category\"]",
      "[class*=\"comment\"]",
      "[id*=\"comment\"]",
      "[class*=\"disqus\"]",
      "[id*=\"disqus\"]",
      "[class^=\"skip\"]",
      "[class*=\"accessib\"]",
      ".sr-only",
      ".visually-hidden",
      "[class*=\"-ad-\"]",
      "[class*=\"_ad_\"]",
      "[class$=\"-ad\"]",
      "[class$=\"_ad\"]",
      "[class^=\"ad-\"]",
      "[class^=\"ad_\"]",
      "[class*=\"advert\"]",
      ".sidebar",
      "#sidebar",
      "[class*=\"sidebar\"]",
      "[class*=\"sider\"]",
      "[class^=\"menu-\"]",
      "[class^=\"menu_\"]",
      "[class$=\"_module\"]",
      "[class$=\"-module\"]",
      "[class*=\"breadcrumb\"]",
      "[class*=\"pagination\"]",
      "[class*=\"relate\"]",
      "[class*=\"recommend\"]",
      "[class*=\"trending\"]",
      "[class^=\"header-\"]",
      "[class$=\"-header\"]",
      "[class^=\"header_\"]",
      "[class$=\"_header\"]",
      "[class*=\"footer\"]",
      "[class$=\"-offset\"]",
      "[class*=\"-offset-\"]",
      "[class$=\"_offset\"]",
      "[class*=\"_offset_\"]"
  ],
  "maxAge": 172800000,
  "headers": {},
  "waitFor": 0,
  "mobile": false,
  "skipTlsVerification": true,
  "timeout": 30000,
  "parsers": ["pdf"],
  "removeBase64Images": true,
  "blockAds": true,
  "proxy": "auto",
  "storeInCache": true
}
'